### ISSUE TITLE
options.prefix doesn't appear to work

### ISSUE THREAD

**Issue by geek** [flatiron/restful#11]
When trying out

app.use(restful, { prefix: '/api' })

with a resource for user, the URL at /api/users doesn't work.  I believe this is due to the controller not properly respecting if a resource was prefixed with a parent path, but I may be wrong about that.

Being able to put all of the endpoints under a common path seems useful.  Is there another way in which I should be doing this or is prefix the recommended approach?

Thanks.

**Comment by Marak** [comment]
Good catch! 

`option.prefix` was actually intended for internal use, but what you ask makes sense.

I'll add this soon. Thanks for the feedback.

**Comment by pksunkara** [comment]
Fixed.
