### ISSUE TITLE
Missing param merging / query string parsing logic

### ISSUE THREAD

**Issue by Marak** [flatiron/restful#12]
Currently, `restful` doesn't respect any incoming URL query string parameters. ( Everything so far has been done via req body ).

We should use https://github.com/visionmedia/node-querystring/ to parse incoming query strings.

The parsed query string params should be intelligently merged with any req.body data into a common `params` scope.

**Comment by jfhbrook** [comment]
Director handlers have the querystring parsed and in `req.query` if memory serves.

**Comment by pksunkara** [comment]
yes, director have them req.query

**Comment by Marak** [comment]
Ok, then show me how to do this in director:

Input:

```
 http://localhost:8000/foo?user[name][first]=Tobi&user[email]=tobi@learnboost.com
```

Output:

```
 { user: { name: { first: 'Tobi' }, email: 'tobi@learnboost.com' } }
```

**Comment by Marak** [comment]
Pretty sure I just reconfirmed my original suspicion, in that you can't.

See: https://github.com/flatiron/director/blob/master/lib/director/http/index.js#L2

Currently using node's core `querystring` module which doesn't support nested params out of the box and we need those for relational data, hence the reason I said use `qs` module.

**Comment by pksunkara** [comment]
hmm.. Can we use `qs` in director itself?

**Comment by Marak** [comment]
Feel free to open up an issue in Director if you want @pksunkara.

**Comment by Marak** [comment]
invalid
