### ISSUE TITLE
n-level resource relationships

### ISSUE THREAD

**Issue by Marak** [flatiron/restful#13]
Currently, restful can only reflect relationships that are one level deep.

ex: `Songs => Albums`

restful should be able to work with any amount of relational levels. 

ex: `Songs => Artists => Albums`

This should be relatively easy since we are already using a recursive traversal to generate the routing maps.

**Comment by terite** [comment]
Has any progress been made on this issue?

**Comment by pksunkara** [comment]
Fixed.
