### ISSUE TITLE
POST / create doesn't trigger validation?

### ISSUE THREAD

**Issue by raix** [flatiron/restful#18]
Just made a small test on node.js with firefox RESTClient - looks good, except:

I'm allowed to create new creatures with "life" out of bounce eg. life=4 or 24
Im expecting an validation error. The defaults reads in correct if not set at creation, but seems like input doesn't get validated?
Short:
var Creature    = resourceful.define('creature');
Creature.property('type', String, { default: "dragon" });
Creature.property('life', Number, { default: 10, min: 0, max: 20 });

**Comment by Marak** [comment]
I can confirm that the min / max constraints on Numbers are not working.

I don't think the issue is in restful, but rather resourceful for revalidator. I'll get this sorted out soon. 

If you'd like to help, you can add a test here: https://github.com/flatiron/restful/blob/master/test/macros/index.js#L387

Thanks!

**Comment by raix** [comment]
ok, well I'm kinda new in github and node - I've forked the project and added the test for validation, it fails as it should.
I've changed test/fixtures L91:   this.number('age', { message: 'is not a valid age', default: 10, min: 0, max: 100 });
Dont know if that is the correct syntax for validation, the resourceful wiki doesn't say
and added to macro.typeValidationTest:
.next()
  .post('/user', { email: "mh@gi-software.com", age: 200})
    .expect(422)

How does it work in git, if I push/commit to my forked version is that merged(able) to yours?

**Comment by Marak** [comment]
@raix - It's all good, welcome!

The general work-flow would be: **Fork** => **Commit** => **Push to Fork** => **Open Pull Request**. From there, we can review and merge.

As for resourceful documentation, we need more of it. see: https://github.com/flatiron/resourceful/issues/91 :-)

I think that syntax is right, best way to test, is to create a resource in memory ( without restful ) and just trying to create or save a new instance and see what happens.

**Comment by raix** [comment]
I kinda solved the thing anyway though, by reading the resourceful code.
The restful readme.md says "Creature.property('life', Number, { default: 10, min: 0, max: 20 });" should be:
Creature.property('life', Number, { default: 10, minimum: 0, maximum: 20 });

I'll try committing, my eclipse egit stopped working, think I'll tryout som git for sublime t2 later
