### ISSUE TITLE
npm install restful gives the error: npm WARN install Refusing to install restful as a dependency of itself 

### ISSUE THREAD

**Issue by nehajatav** [flatiron/restful#21]

**Comment by Marak** [comment]
Hello.

That doesn't sound right. I just confirmed an install from npm right now. You should upgrade your npm to the latest version and try again.

If that doesn't work out, paste your entire NPM log along with your `node -v` and `npm -v` versions

**Comment by nehajatav** [comment]
I did a npm update & it worked :)
