### ISSUE TITLE
Support many-to-many relationships

### ISSUE THREAD

**Issue by nrw** [flatiron/restful#25]
[this example](https://github.com/flatiron/resourceful/blob/master/examples/relationship-many-to-many.js) from the `resourceful` repo throws `Maximum call stack size exceeded`.

**Comment by pksunkara** [comment]
That example is wrong. Many-to-Many doesnt work like that in resourceful.

**Comment by nrw** [comment]
Where can I find an example of how to use many-to-many relationships in resourceful?

**Comment by pksunkara** [comment]
@nrw Please go through relationships-test.js. We will document it soon.

**Comment by nrw** [comment]
@pksunkara I don't see any examples of creating many-to-many relationships in the tests. Can you point me to a line number?

**Comment by pksunkara** [comment]
Sorry, I thought it was in tests, but it's in a gist. https://gist.github.com/3984327

**Comment by nrw** [comment]
thanks
