### ISSUE TITLE
Scope entity returned inside property with same name

### ISSUE THREAD

**Issue by indexzero** [flatiron/restful#3]
This is a convention we've followed for a long time @cronopio 

```
GET /user/:id

{
  user: {
    ...
  }
}
```

Currently `restful` will not respect this scoping. i.e.

```
GET /user/:id

{
  ...
}
```

To stay compliant with our current conventions we should fix this.

**Comment by cronopio** [comment]
Ok, I guess the nested result depend of the resource name. I mean if you define a "Car" resource should respond:

```
GET /car/:id

{
  car: {
    ....
  }
}
```

If correct, then well understood

Also I have to do a more detailed review to restful. 
Thanks @indexzero

**Comment by indexzero** [comment]
@cronopio Yes, this is what I meant.
