### ISSUE TITLE
peerDependencies: current restful wants last-versions resourceful

### ISSUE THREAD

**Issue by eins78** [flatiron/restful#31]
Is this a bug in the sense that the package.json was not updated or are there real issues to be solved before using restful with resourceful >0.3.0 ?

``` sh
npm ERR! peerinvalid The package resourceful does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer restful@0.2.2 wants resourceful@0.2.x
```

**Comment by pvorb** [comment]
@eins78 I didn't see your issue before posting my own (#33).

I think, you can prevent this error by explicitly installing the newest version (v0.4.4).

```
npm install restful@0.4.4
```

If you are depending on restful from another project, update your dependencies in the `package.json` to use `"restful": "~0.4.4"` or something like that.

Hope this helps.

**Comment by eins78** [comment]
(closing it since it was duplicated by #33, which contains actual useful info and research :+1:)
