### ISSUE TITLE
Feature request: Include 'Content-Type' header in response.

### ISSUE THREAD

**Issue by alaendle** [flatiron/restful#32]
I think this would improve interoperability with 3rd-party tools (e.g. diagnostic tools would know how to interpret the response). A very simple solution would be to include "res.writeHead(status, { 'Content-Type': 'application/json' });" in restful.js/respondWithResult(req, res, status, key, value). At least this is my current workaround.

**Comment by pvorb** [comment]
As long as my pull request doesn't get merged, you can provide your own `respond()` function without modifying Restful. Therefore, you have to set it in the `options` object passed to `app.use()` or when creating the standalone router.

Here's an example for Flatiron:

``` javascript
// ...
var restful = require('restful');
var flatiron = require('flatiron');
var app = flatiron.app;

app.resources = resources // an array of Resources

function customRespond(req, res, status, key, value) {
  var result;
  res.writeHead(status, { 'Content-Type': 'application/json' });

  if (arguments.length === 5) {
    result = {};
    result[key] = value;
  }
  else {
    result = key;
  }

  res.end(result ? JSON.stringify(result) : '');
}

app.use(restful, { respond: customRespond }); // use custom respond function
```

**Comment by alaendle** [comment]
@pvorb Many thanks!
