### ISSUE TITLE
Proper Inflection for routes

### ISSUE THREAD

**Issue by activestylus** [flatiron/restful#5]
I see this is flagged as a TODO in the source.

Way I see it there are two options:

https://github.com/dreamerslab/node.inflection
Which is pretty robust. (Probably overkill IMO)

OR

https://github.com/rbgrouleff/simple-inflection
Which is stupidly simple and seems more in line with Flatiron's minimal philosophy.

What do you guys think?

**Comment by activestylus** [comment]
Actually there is a third option, by a flatiron contributor no less ( @pksunkara ): https://github.com/pksunkara/inflect

**Comment by pksunkara** [comment]
@Marak, we are already using  https://github.com/pksunkara/inflect in resourceful. So, you might wanna use it for this.

**Comment by Marak** [comment]
Closed with https://github.com/flatiron/restful/commit/95c2063e51c1c4ab04eb369a40daee722e5bb68b
